@extends('layouts.app')
@section('title', 'Proceso de Notificaciones')
@include('partials.datatables-export-assets')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0">Proceso de Notificaciones</h1><span class="text-muted">Expedientes, no historial de consultas</span></div>
<div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Expedientes</small><h3 class="mb-0">{{ number_format($kpis['total']) }}</h3></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Pendientes</small><h3 class="mb-0 text-danger">{{ number_format($kpis['pending']) }}</h3></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">En revisión</small><h3 class="mb-0 text-warning">{{ number_format($kpis['review']) }}</h3></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Validados</small><h3 class="mb-0 text-success">{{ number_format($kpis['validated']) }}</h3></div></div></div></div>
<form method="GET" class="card card-body shadow-sm mb-3"><div class="row g-2">
<div class="col-md-2"><label class="form-label" for="folio">Folio</label><input class="form-control" id="folio" name="folio" value="{{ request('folio') }}"></div>
<div class="col-md-2"><label class="form-label" for="vin">VIN</label><input class="form-control" id="vin" name="vin" value="{{ request('vin') }}"></div>
<div class="col-md-3"><label class="form-label" for="user_id">Responsable</label><select class="form-select" id="user_id" name="user_id"><option value="">Todos</option>@foreach($owners as $owner)<option value="{{ $owner->id }}" @selected((string)request('user_id') === (string)$owner->id)>{{ $owner->name }} ({{ $owner->email }})</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label" for="status">Estado</label><select class="form-select" id="status" name="status"><option value="">Todos</option>@foreach(\App\Domain\NotificationCases\Enums\NotificationCaseStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div>
<div class="col-md-1"><label class="form-label" for="date_from">Desde</label><input type="date" class="form-control" id="date_from" name="date_from" value="{{ request('date_from') }}"></div>
<div class="col-md-1"><label class="form-label" for="date_to">Hasta</label><input type="date" class="form-control" id="date_to" name="date_to" value="{{ request('date_to') }}"></div>
<div class="col-md-1 d-flex align-items-end"><button class="btn btn-primary w-100">Filtrar</button></div></div></form>
<div class="card shadow-sm"><div class="table-responsive"><table id="adminNotificationCases" class="table table-hover align-middle mb-0 w-100"><thead><tr><th>Folio / VIN</th><th>Responsable</th><th>Vehículo</th><th>Apertura / límite</th><th>Estado</th><th>Envío / actualización</th><th></th></tr></thead><tbody>
@forelse($cases as $case)<tr class="{{ $case->status->value === 'SUBMITTED' ? 'table-warning' : ($case->status->value === 'UNDER_REVIEW' ? 'table-info' : '') }}"><td><strong>{{ $case->case_number }}</strong><br><small>{{ $case->vin ?: 'VIN NO DISPONIBLE' }}</small></td><td>{{ $case->owner?->name }}<br><small>{{ $case->owner?->email }}</small></td><td>{{ $case->make }} {{ $case->model }} {{ $case->model_year }}<br><small>{{ $case->license_plate }}</small></td><td data-order="{{ $case->opened_at?->timestamp }}">{{ $case->opened_at?->format('d/m/Y H:i') }}<br><small>Límite {{ $case->notification_deadline_at->format('d/m/Y H:i:s') }}</small></td><td><span class="badge text-bg-{{ $case->status->value === 'VALIDATED' ? 'success' : ($case->status->value === 'PENDING' ? 'danger' : 'warning') }}">{{ $case->status->label() }}</span><br><small>{{ $case->active_documents_count }} evidencias</small></td><td data-order="{{ $case->updated_at?->timestamp }}">{{ $case->last_submitted_at?->format('d/m/Y H:i') ?: 'Sin envío' }}<br><small>{{ $case->updated_at?->format('d/m/Y H:i') }}</small></td><td><a class="btn btn-sm btn-primary" href="{{ route('admin.notification-cases.show', $case) }}">Revisar</a></td></tr>
@empty<tr><td colspan="7" class="text-center text-muted py-4">No hay expedientes con esos filtros.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
@push('scripts')<script>$(function(){$('#adminNotificationCases').DataTable({ordering:true,searching:true,pageLength:10,language:{url:@json(asset('vendor/vintrack/datatables-es-ES-1.13.6.json')),search:'Búsqueda rápida:'},dom:"<'vintrack-table-toolbar row g-3 align-items-center px-3 pt-3'<'col-lg-6'B><'col-lg-6'f>>rt<'row px-3 py-3'<'col-md-5'i><'col-md-7 d-flex justify-content-md-end'p>>",buttons:[{extend:'excelHtml5',text:'<i class="bi bi-file-earmark-excel me-1"></i> Excel',className:'buttons-excel',title:'Proceso de Notificaciones',filename:'proceso-notificaciones',exportOptions:{columns:[0,1,2,3,4,5]}},{extend:'pdfHtml5',text:'<i class="bi bi-file-earmark-pdf me-1"></i> PDF',className:'buttons-pdf',title:'Proceso de Notificaciones',filename:'proceso-notificaciones',orientation:'landscape',exportOptions:{columns:[0,1,2,3,4,5]}}],columnDefs:[{targets:6,orderable:false,searchable:false}]});});</script>@endpush
