@extends('layouts.app')

@section('title', 'Historial Global de Vehículos Consultados')
@include('partials.datatables-export-assets')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="mb-1">Historial Global de Vehículos Consultados</h2><p class="text-muted mb-0">Universo autorizado de consultas y su proceso documental aplicable.</p></div></div>
<div class="row g-3 mb-4"><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Resultados</small><h3 id="history-total" class="mb-0">0</h3></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">En esta página</small><h3 id="history-page" class="mb-0">0</h3></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Robo positivo</small><h3 id="history-theft" class="mb-0 text-danger">0</h3></div></div></div><div class="col-6 col-xl-3"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">Validados</small><h3 id="history-validated" class="mb-0 text-success">0</h3></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-3 align-items-end">
    <div class="col-md-3"><label class="form-label" for="user_id">Cliente</label><select id="user_id" class="form-select history-filter"><option value="">Todos</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }} ({{ $user->email }})</option>@endforeach</select></div>
    <div class="col-md-2"><label class="form-label" for="date_from">Desde</label><input id="date_from" type="date" class="form-control history-filter"></div>
    <div class="col-md-2"><label class="form-label" for="date_to">Hasta</label><input id="date_to" type="date" class="form-control history-filter"></div>
    <div class="col-md-2"><label class="form-label" for="vin">VIN</label><input id="vin" maxlength="32" class="form-control history-filter"></div>
    <div class="col-md-2"><label class="form-label" for="plate">Placas</label><input id="plate" maxlength="32" class="form-control history-filter"></div>
    <div class="col-md-2"><label class="form-label" for="theft_status">Status robo</label><select id="theft_status" class="form-select history-filter"><option value="">Todos</option><option>POSITIVO</option><option>NEGATIVO</option></select></div>
    <div class="col-md-3"><label class="form-label" for="case_status">Estado del proceso</label><select id="case_status" class="form-select history-filter"><option value="">Todos</option><option value="NO_CASE">NO APLICA</option>@foreach(\App\Domain\NotificationCases\Enums\NotificationCaseStatus::cases() as $status)<option value="{{ $status->value }}">{{ $status->label() }}</option>@endforeach</select></div>
</div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><div class="table-responsive"><table id="globalHistory" class="table table-hover align-middle w-100"><thead><tr>
<th>Fecha</th><th>Cliente</th><th>VIN</th><th>Placas</th><th>Marca</th><th>Modelo</th><th>Año</th><th>Servicio</th><th>Status robo</th><th>Notificado</th><th>Validado</th><th>Fecha límite</th><th>Estado general</th><th>Acciones</th>
</tr></thead></table></div></div></div>
@endsection

@push('scripts')
<script>
$(function(){const esc=v=>$('<div>').text(v??'—').html(),badge=v=>`<span class="badge text-bg-${v==='VALIDATED'?'success':(v==='PENDING'?'danger':'warning')}">${esc(v)}</span>`;const table=$('#globalHistory').DataTable({processing:true,serverSide:true,pageLength:10,lengthMenu:[10,25,50,100],searchDelay:350,order:[[0,'desc']],dom:"<'vintrack-table-toolbar row g-3 align-items-center px-3 pt-3'<'col-lg-6'B><'col-lg-6'f>>rt<'row px-3 py-3'<'col-md-5'i><'col-md-7 d-flex justify-content-md-end'p>>",buttons:[{extend:'excelHtml5',text:'<i class="bi bi-file-earmark-excel me-1"></i> Excel',className:'buttons-excel',title:'Historial Global de Vehículos Consultados',filename:'historial-global-vehiculos',exportOptions:{columns:[0,1,2,3,4,5,6,7,8,9,10,11,12]}},{extend:'pdfHtml5',text:'<i class="bi bi-file-earmark-pdf me-1"></i> PDF',className:'buttons-pdf',title:'Historial Global de Vehículos Consultados',filename:'historial-global-vehiculos',orientation:'landscape',exportOptions:{columns:[0,1,2,3,4,5,6,7,8,9,10,11,12]}}],ajax:{url:@json(route('admin.consultations.data')),data:d=>{$('.history-filter').each(function(){d[this.id]=this.value;});}},columns:[
{data:'consulted_at'},{data:'user',render:u=>u?`${esc(u.name)}<small class="d-block text-muted">${esc(u.email)}</small>`:'—'},{data:'vin'},{data:'license_plate'},{data:'make'},{data:'model'},{data:'model_year'},{data:'service'},{data:'theft_status'},{data:'notified_status'},{data:'validated_status'},{data:'notification_deadline',defaultContent:'—'},{data:'general_status',render:badge},{data:'actions',orderable:false,searchable:false,render:actions=>actions?.length?actions.map(action=>`<a class="btn btn-sm btn-outline-primary me-1" href="${esc(action.url)}">${action.type==='report'?'&#128196; ':''}${esc(action.label)}</a>`).join(''):'—'}],language:{url:'{{ asset('vendor/vintrack/datatables-es-ES-1.13.6.json') }}',search:'Búsqueda rápida:'}});table.on('xhr',(_,__,json)=>{const rows=json.data||[];$('#history-total').text(json.recordsFiltered||0);$('#history-page').text(rows.length);$('#history-theft').text(rows.filter(row=>row.theft_status==='POSITIVO').length);$('#history-validated').text(rows.filter(row=>row.general_status==='VALIDATED').length);});$('.history-filter').on('change input',()=>table.ajax.reload());});
</script>
@endpush
